name:    hack-skull
version: 0.0.1.0
github:  "tycobb/hack-skull"
license: GPL-3
author:  "Ty Cobb"
extra-source-files:
- README.md

dependencies:
- base  >= 4.7 && < 5
- split >= 0.2 && < 1

library:
  source-dirs: src

executables:
  hack-skull-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack-skull

tests:
  hack-skull-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack-skull
